Fix null language id problem while creating new books
uwblueprint/poly pull request #6
Opened 2018-03-27 03:17 UTC by lazypanda10117

2018-03-27 03:35 UTC, ioanacrant requested changes

2018-03-27 03:35 UTC, ioanacrant commented on app/controllers/books_controller.rb
>        # TODO: verbatim search source_language in ontology, and set id if there is a result
remove this comment?

2018-03-27 03:35 UTC, ioanacrant commented on app/controllers/books_controller.rb
> +    parsed_result = (json_obj != nil) ? json_obj[0]['glottocode'] : nil
we should only be setting the glottocode if we are sure there's only one matching entity, e.g. if the json result is of length 1

2018-03-28 17:33 UTC, baieric approved these changes
could you remove the gemfile.lock and the NewBook.es6.jsx changes from this commit? Otherwise good to go.

2018-03-29 06:58 UTC, merged